// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingApi.Data;

#nullable disable

namespace TicketingApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TicketingApi.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Network",
                            CreatedAt = new DateTime(2026, 8, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "I cannot connect to the company VPN since this morning. Error: timeout.",
                            Priority = "High",
                            Status = "Open",
                            Title = "Cannot connect to VPN"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Software",
                            CreatedAt = new DateTime(2026, 8, 11, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Microsoft Excel crashes every time I try to open a file larger than 5 MB.",
                            Priority = "Medium",
                            Status = "InProgress",
                            Title = "Excel keeps crashing"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Hardware",
                            CreatedAt = new DateTime(2026, 8, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "My current laptop is 5 years old and very slow. Requesting a replacement.",
                            Priority = "Low",
                            Status = "Open",
                            Title = "Request new laptop"
                        });
                });

            modelBuilder.Entity("TicketingApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@ticketing.com",
                            FullName = "Admin User",
                            PasswordHash = "$2a$11$PlcGmX0mYeEX1yU/gVdxCueS.zxI/GVjvbRXhqJR7zpgEEKuI54tO",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "agent@ticketing.com",
                            FullName = "Support Agent",
                            PasswordHash = "$2a$11$Ru9NZ8ZyU2h9F3/euXJ0ve1hjh7lIlDK932o1WUkIH2G4qb/9gPYG",
                            Role = "Agent"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "user@ticketing.com",
                            FullName = "Regular User",
                            PasswordHash = "$2a$11$tB24ROgFbFQ3ezh0eX8QOuR0TY3SKubo5JP5IVBqH6O48oXwOtIbW",
                            Role = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
